#!/usr/bin/env bash

#volume
if [[ `pactl list sinks | grep Mute | grep y` ]];
then
    printf " $(amixer sget Master | grep 'dB' | awk -F'[][]' ' { print $2 }')%";
else
    printf " $(amixer sget Master | grep 'dB' | awk -F'[][]' ' { print $2 }')%";
fi
